<script lang="ts">
  import { ListTree, ShieldCheck } from "lucide-svelte";
  import { approveBaseline, getSelectedTransaction, ui } from "../stores.svelte";
  const selectedTransaction = $derived(getSelectedTransaction());
  const tab = $derived(ui.tab);
  const setTab = (next: Tab) => ui.tab = next;
  import { bodyText, durationMs, prettyJson, transactionState } from "../lib";
  import type { Tab } from "../lib";

  const TABS: Tab[] = ["Overview", "Request", "Response", "Compare", "cURL", "Timeline"];
</script>

<aside class="inspector">{#if selectedTransaction}{@const tx = selectedTransaction}<div class="inspector-heading"><div><span>{tx.request.method}</span><b>{tx.request.host}{tx.request.path}</b></div></div><nav class="tabs">{#each TABS as name}<button class:active={tab === name} onclick={() => setTab(name)}>{name}</button>{/each}</nav><div class="detail-panel">{#if tab === "Overview"}<div class="overview-grid"><label>Status<b>{tx.response?.status ?? "Pending"}</b></label><label>Duration<b>{durationMs(tx) ?? "—"} ms</b></label><label>Content type<b>{tx.response?.content_type || tx.request.content_type || "Unknown"}</b></label><label>Capture quality<b>{tx.capture_quality}</b></label></div>{:else if tab === "Request" || tab === "Response"}{@const message = tab === "Request" ? tx.request : tx.response}<h3>{tab} headers</h3><div class="header-list">{#each message?.headers || [] as header}<div><b>{header.name}</b><span>{header.value}</span></div>{/each}</div><h3>Body</h3><pre>{prettyJson(bodyText(message?.body))}</pre>{:else if tab === "Compare"}<div class="compare-summary"><div><span>JSON shape comparison</span><b>{tx.comparison ? tx.comparison.compatibility.replaceAll("_", " ") : "Waiting for a comparable response"}</b><small>Scalar values are ignored; only JSON keys, nesting, array item shapes, and types are compared.</small></div><button class="quiet" onclick={() => void approveBaseline(tx)}>Set baseline</button></div>{#if tx.comparison?.differences.length}<div class="difference-list">{#each tx.comparison.differences as difference}<article class:critical={difference.severity === "critical"} class:ignored={difference.ignored}><div><b>{difference.kind.replaceAll("_", " ")}</b><code>{difference.path || "Response"}</code></div><p>{difference.explanation}</p>{#if difference.previous || difference.current}<small><span>Before: {difference.previous || "—"}</span><span>After: {difference.current || "—"}</span></small>{/if}</article>{/each}</div>{:else}<div class="compare-empty"><ShieldCheck/><b>{tx.comparison ? "No JSON-key changes" : "No comparison yet"}</b><span>{tx.comparison ? "This response matches the observed JSON shape." : "Set a baseline or wait for another response to this endpoint."}</span></div>{/if}{:else if tab === "cURL"}<pre>{tx.curl?.multiline || "cURL will be generated once the request is complete."}</pre>{:else}<ol class="timeline"><li>Request started <time>{new Date(tx.timing.request_started_ms).toLocaleTimeString()}</time></li>{#if tx.timing.request_complete_ms}<li>Request sent</li>{/if}{#if tx.timing.response_started_ms}<li>Response headers received</li>{/if}{#if tx.timing.response_complete_ms}<li>Response complete</li>{/if}</ol>{/if}</div>{:else}<div class="empty-state inspector-empty"><ListTree size={30}/><b>Select a request</b><span>Its headers, body and timing will appear here.</span></div>{/if}</aside>
