name: app_tester_companion
description: Android desktop-link companion for App Tester.
publish_to: none
version: 0.3.6+13

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
