name: app_tester_companion
description: Android desktop-link companion for App Tester.
publish_to: none
version: 0.2.3+5

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: 6.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
