//! Turns a composed body into a wire payload.
//!
//! Form bodies are encoded here so the stored request bytes match the sent
//! bytes exactly. Multipart bodies stream from disk via reqwest and are never
//! buffered; their exact wire bytes are therefore not stored.

use reqwest::multipart::{Form, Part};

use super::model::{ManualBody, MultipartField, SendError};

/// The prepared payload plus the content type to attach when the user did
/// not set one explicitly.
pub enum PreparedBody {
    None,
    /// Pre-encoded `application/x-www-form-urlencoded` body
    Form {
        encoded: String,
    },
    /// Multipart form; reqwest generates the boundary itself
    Multipart(Form),
    /// Raw bytes (text, JSON, binary)
    Raw(Vec<u8>),
}

impl PreparedBody {
    /// Content type owned by the body kind, if any. `None` for multipart
    /// (its boundary is generated by reqwest) and raw bodies (their media
    /// type is user-supplied).
    pub fn content_type(&self) -> Option<&'static str> {
        match self {
            Self::Form { .. } => Some("application/x-www-form-urlencoded"),
            Self::None | Self::Multipart(_) | Self::Raw(_) => None,
        }
    }

    /// The exact bytes that will be sent, for storage. Empty for multipart.
    pub fn wire_bytes(&self) -> &[u8] {
        match self {
            Self::None => &[],
            Self::Form { encoded } => encoded.as_bytes(),
            Self::Raw(bytes) => bytes,
            Self::Multipart(_) => &[],
        }
    }
}

pub async fn prepare(body: &ManualBody) -> Result<PreparedBody, SendError> {
    match body {
        ManualBody::None => Ok(PreparedBody::None),
        ManualBody::Form { fields } => Ok(PreparedBody::Form {
            encoded: encode_urlencoded(fields),
        }),
        ManualBody::Raw { text, .. } => Ok(PreparedBody::Raw(text.as_bytes().to_vec())),
        ManualBody::Binary { bytes } => Ok(PreparedBody::Raw(bytes.clone())),
        ManualBody::Multipart { fields } => {
            Ok(PreparedBody::Multipart(build_multipart(fields).await?))
        }
    }
}

/// `application/x-www-form-urlencoded` encoding, RFC 3986 unreserved set.
pub fn encode_urlencoded(fields: &[(String, String)]) -> String {
    fields
        .iter()
        .map(|(name, value)| format!("{}={}", percent_encode(name), percent_encode(value)))
        .collect::<Vec<_>>()
        .join("&")
}

fn percent_encode(input: &str) -> String {
    let mut encoded = String::with_capacity(input.len());
    for byte in input.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                encoded.push(byte as char);
            }
            b' ' => encoded.push('+'),
            other => encoded.push_str(&format!("%{other:02X}")),
        }
    }
    encoded
}

async fn build_multipart(fields: &[MultipartField]) -> Result<Form, SendError> {
    let mut form = Form::new();
    for field in fields {
        let name = field.name.clone();
        if let Some(path) = &field.file {
            let mut part = Part::file(path)
                .await
                .map_err(|source| SendError::MultipartFile {
                    path: path.clone(),
                    source,
                })?;
            if let Some(media_type) = &field.media_type {
                part = part
                    .mime_str(media_type)
                    .map_err(|error| SendError::Request(error.to_string()))?;
            }
            form = form.part(name, part);
        } else {
            form = form.text(name, field.value.clone().unwrap_or_default());
        }
    }
    Ok(form)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn urlencoded_encodes_reserved_characters_and_spaces() {
        let encoded = encode_urlencoded(&[
            ("name".into(), "two words".into()),
            ("emoji".into(), "🙂".into()),
            ("special".into(), "a&b=c".into()),
        ]);
        assert_eq!(
            encoded,
            "name=two+words&emoji=%F0%9F%99%82&special=a%26b%3Dc"
        );
    }

    #[test]
    fn urlencoded_keeps_unreserved_characters_untouched() {
        let encoded = encode_urlencoded(&[("key".into(), "AZaz09-_.~".into())]);
        assert_eq!(encoded, "key=AZaz09-_.~");
    }

    #[test]
    fn prepared_body_exposes_content_types_and_wire_bytes() {
        let form = PreparedBody::Form {
            encoded: "a=1".into(),
        };
        assert_eq!(
            form.content_type(),
            Some("application/x-www-form-urlencoded")
        );
        assert_eq!(form.wire_bytes(), b"a=1");
        assert_eq!(PreparedBody::None.wire_bytes(), b"");
        assert_eq!(PreparedBody::Raw(vec![9]).content_type(), None);
    }

    #[tokio::test]
    async fn multipart_builds_text_and_file_parts() {
        let directory =
            std::env::temp_dir().join(format!("composer-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&directory).unwrap();
        let file_path = directory.join("payload.bin");
        std::fs::write(&file_path, b"file-bytes").unwrap();

        let form = build_multipart(&[
            MultipartField {
                name: "note".into(),
                value: Some("hello".into()),
                file: None,
                media_type: None,
            },
            MultipartField {
                name: "upload".into(),
                value: None,
                file: Some(file_path.to_string_lossy().into_owned()),
                media_type: Some("application/octet-stream".into()),
            },
        ])
        .await
        .unwrap();

        // Form is not Clone; verify by rendering its boundary and fields.
        let boundary = form.boundary();
        assert!(boundary.len() >= 16, "reqwest generates a random boundary");
        let _ = std::fs::remove_dir_all(&directory);
    }
}
